### ISSUE TITLE
cannot disable left swipe for stand alone swiperow.

### ISSUE THREAD

**Issue by chirag04** [jemise111/react-native-swipe-list-view#1]
I'm trying to use the standalone swipe row component but seems like it always swipe to left.

**Comment by jemise111** [comment]
Hey @chirag04, would you mind pasting the code where you're using the SwipeRow and I'll have a look? 
Thanks!

**Comment by benoitvallon** [comment]
I am not sure if it is related to this issue but it would be nice to be able to lock a side of the row to avoid the swipe. The `leftOpenValue` sets to 0 avoids the swipe to open the row, but if the row cannot be opened I think it would make sense not to have the swipe gesture as well.

**Comment by jemise111** [comment]
Ah, I understand now. Yeah it's something I didn't get around to in the initial release. Will try to work on later today but PRs are welcome ;)

For flexibility's  sake maybe instead of disabling when the value is 0 there could be disableLeftSwipe and disableRightSwipe props?

**Comment by benoitvallon** [comment]
Yes I agree, the new props disableXxxxSwipe would make the lib more flexible instead of doing it for 0.

**Comment by jemise111** [comment]
Fixed by #6. You can now use **disableLeftSwipe** and **disableRightSwipe** props on the SwipeListView or SwipeRow

**Comment by Burak07** [comment]
I afraid this issue still exists. DisableRightSwap works but DisableLeftSwap doesn't work if swipeListView has renderHiddenRow property. After removing this property both works well.

**Comment by lyair1** [comment]
Hey @Burak07 you could return "undefined" for the row that you want to disable the swipe for.

e.g.

`renderHiddenItem={(data, rowMap) => data.item.id == 5 ? <HiddenComponent id={data.item.id} /> : undefined}`

hope this helps
